/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prison_Management_System;
import static Prison_Management_System.Login.username;
import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author amits
 */
public class InsertOrUpdate_Details extends javax.swing.JFrame {

    /**
     * Creates new form Insert_Details
     */
    public InsertOrUpdate_Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Court_ID = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Chief_Justice = new javax.swing.JTextField();
        Jury = new javax.swing.JTextField();
        Level = new javax.swing.JTextField();
        Submit_Court = new javax.swing.JButton();
        Update_Court = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Type = new javax.swing.JTextField();
        Court_ID_Case = new javax.swing.JTextField();
        Verdict = new javax.swing.JTextField();
        Verdict_Date = new javax.swing.JTextField();
        Charges = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Submit_Case = new javax.swing.JButton();
        Case_ID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Update_Case = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Prison_ID = new javax.swing.JTextField();
        Prison_Location = new javax.swing.JTextField();
        Jurisdiction = new javax.swing.JTextField();
        Submit_Prison = new javax.swing.JButton();
        Update_Prison = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Staff_Salary = new javax.swing.JTextField();
        Staff_Designation = new javax.swing.JTextField();
        Staff_Address = new javax.swing.JTextField();
        Staff_ID = new javax.swing.JTextField();
        Staff_DoB = new javax.swing.JTextField();
        Submit_Staff = new javax.swing.JButton();
        Staff_Name = new javax.swing.JTextField();
        Update_Staff = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Inmate_ID = new javax.swing.JTextField();
        Release_Date = new javax.swing.JTextField();
        Alias = new javax.swing.JTextField();
        Inmate_Name = new javax.swing.JTextField();
        Start_Date = new javax.swing.JTextField();
        Inmate_DoB = new javax.swing.JTextField();
        Case_ID_Inmate = new javax.swing.JTextField();
        Prison_ID_Inmate = new javax.swing.JTextField();
        Supervisor_Staff_ID = new javax.swing.JTextField();
        Submit_Inmate = new javax.swing.JButton();
        Update_Inmate = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        Job_ID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Job_Description = new javax.swing.JTextArea();
        Submit_Job_Desc = new javax.swing.JButton();
        Update_Job_Info = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Job_ID_Feedback = new javax.swing.JTextField();
        Inmate_ID_Feedback = new javax.swing.JTextField();
        Shift = new javax.swing.JTextField();
        Hours_Completed = new javax.swing.JTextField();
        Submit_Job = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Feedback = new javax.swing.JTextArea();
        Update_Job = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        Visitor_Name = new javax.swing.JTextField();
        Contact_Number = new javax.swing.JTextField();
        Inmate_ID_Visitor = new javax.swing.JTextField();
        Relationship = new javax.swing.JTextField();
        Purpose = new javax.swing.JTextField();
        Entry_Time = new javax.swing.JTextField();
        Submit_Visitor = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        Exit_Time = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel6.setText("Court_ID");

        jLabel9.setText("Address");

        jLabel10.setText("Chief_Justice");

        jLabel11.setText("Level");

        jLabel12.setText("Jury_Members");

        Jury.setToolTipText("(Enter multiple values separated by comma.)");

        Level.setToolTipText("Supreme/High/District/Sessions/Tribunal");

        Submit_Court.setText("Insert");
        Submit_Court.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_CourtActionPerformed(evt);
            }
        });

        Update_Court.setText("Update");
        Update_Court.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_CourtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Submit_Court)
                        .addGap(18, 18, 18)
                        .addComponent(Update_Court))
                    .addComponent(Chief_Justice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Level, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jury, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Court_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Court_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Chief_Justice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Jury, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit_Court)
                    .addComponent(Update_Court))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Court", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setText("Type");

        jLabel3.setText("Verdict");

        jLabel4.setText("Verdict_Date");

        jLabel5.setText("Court_ID");

        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });

        Verdict_Date.setToolTipText("YYYY-MM-DD");
        Verdict_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Verdict_DateActionPerformed(evt);
            }
        });

        Charges.setToolTipText("(Enter multiple values separated by comma.)");
        Charges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChargesActionPerformed(evt);
            }
        });

        jLabel7.setText("Charges");

        Submit_Case.setText("Insert");
        Submit_Case.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_CaseActionPerformed(evt);
            }
        });

        Case_ID.setToolTipText("(Enter multiple values separated by comma.)");
        Case_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_IDActionPerformed(evt);
            }
        });

        jLabel13.setText("Case_ID");

        Update_Case.setText("Update");
        Update_Case.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_CaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Court_ID_Case, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Submit_Case)
                                .addGap(18, 18, 18)
                                .addComponent(Update_Case))
                            .addComponent(Charges, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Case_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Type, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(Verdict))
                                .addComponent(Verdict_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addContainerGap(55, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Case_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Verdict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Verdict_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Court_ID_Case, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Charges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit_Case)
                    .addComponent(Update_Case))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Case", jPanel1);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jLabel23.setText("Prison_ID");

        jLabel24.setText("Location");

        jLabel25.setText("Jurisdiction");

        Prison_ID.setToolTipText("Ignore on Insertion");

        Jurisdiction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JurisdictionActionPerformed(evt);
            }
        });

        Submit_Prison.setText("Insert");
        Submit_Prison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_PrisonActionPerformed(evt);
            }
        });

        Update_Prison.setText("Update");
        Update_Prison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_PrisonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Prison_Location)
                            .addComponent(Prison_ID)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Submit_Prison)
                                .addGap(18, 18, 18)
                                .addComponent(Update_Prison)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Jurisdiction))))
                .addGap(102, 102, 102))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Prison_ID))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(Prison_Location))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(Jurisdiction))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit_Prison)
                    .addComponent(Update_Prison))
                .addContainerGap(255, Short.MAX_VALUE))
        );

        Prison_ID.getAccessibleContext().setAccessibleDescription("");
        Prison_Location.getAccessibleContext().setAccessibleDescription("");
        Jurisdiction.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Prison", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        jLabel27.setText("Staff_ID");

        jLabel28.setText("Name");

        jLabel29.setText("Date_Of_Birth");

        jLabel30.setText("Designation");

        jLabel31.setText("Address");

        jLabel32.setText("Salary");

        Staff_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_SalaryActionPerformed(evt);
            }
        });

        Staff_Designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_DesignationActionPerformed(evt);
            }
        });

        Staff_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_AddressActionPerformed(evt);
            }
        });

        Staff_ID.setToolTipText("Ignore on Insertion");
        Staff_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_IDActionPerformed(evt);
            }
        });

        Staff_DoB.setToolTipText("YYYY-MM-DD");
        Staff_DoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_DoBActionPerformed(evt);
            }
        });

        Submit_Staff.setText("Insert");
        Submit_Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_StaffActionPerformed(evt);
            }
        });

        Staff_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_NameActionPerformed(evt);
            }
        });

        Update_Staff.setText("Update");
        Update_Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_StaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Staff_Designation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(Staff_Address, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(Submit_Staff)
                                .addGap(18, 18, 18)
                                .addComponent(Update_Staff))
                            .addComponent(Staff_DoB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Staff_Name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Staff_Salary)
                            .addComponent(Staff_ID))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Staff_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(Staff_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(Staff_DoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(Staff_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(Staff_Designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(Staff_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit_Staff)
                    .addComponent(Update_Staff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Staff", jPanel5);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel14.setText("Inmate_ID");

        jLabel15.setText("Name");

        jLabel16.setText("Alias");

        jLabel17.setText("Date_Of_Birth");

        jLabel18.setText("Start_Date");

        jLabel19.setText("Release Date");

        jLabel20.setText("Case_ID");

        jLabel21.setText("Prison_ID");

        jLabel22.setText("Supervisor_Staff_ID");

        Release_Date.setToolTipText("YYYY-MM-DD");

        Alias.setToolTipText("(Enter multiple values separated by comma.)");

        Start_Date.setToolTipText("YYYY-MM-DD");
        Start_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start_DateActionPerformed(evt);
            }
        });

        Inmate_DoB.setToolTipText("YYYY-MM-DD");

        Case_ID_Inmate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_ID_InmateActionPerformed(evt);
            }
        });

        Submit_Inmate.setText("Insert");
        Submit_Inmate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_InmateActionPerformed(evt);
            }
        });

        Update_Inmate.setText("Update");
        Update_Inmate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_InmateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Submit_Inmate)
                        .addGap(18, 18, 18)
                        .addComponent(Update_Inmate))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Supervisor_Staff_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(Prison_ID_Inmate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Case_ID_Inmate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Release_Date, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Start_Date, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Inmate_DoB, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Alias, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Inmate_Name, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Inmate_ID, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Inmate_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Inmate_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Inmate_DoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Start_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Release_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Case_ID_Inmate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(Prison_ID_Inmate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(Supervisor_Staff_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit_Inmate)
                    .addComponent(Update_Inmate))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inmate", jPanel3);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        jLabel33.setText("Job_ID");

        jLabel34.setText("Description");

        Job_ID.setToolTipText("Ignore on Insertion");
        Job_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Job_IDActionPerformed(evt);
            }
        });

        Job_Description.setColumns(20);
        Job_Description.setRows(5);
        jScrollPane2.setViewportView(Job_Description);

        Submit_Job_Desc.setText("Insert");
        Submit_Job_Desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_Job_DescActionPerformed(evt);
            }
        });

        Update_Job_Info.setText("Update");
        Update_Job_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_Job_InfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Submit_Job_Desc)
                        .addGap(18, 18, 18)
                        .addComponent(Update_Job_Info))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Job_ID)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(Job_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit_Job_Desc)
                    .addComponent(Update_Job_Info))
                .addGap(62, 62, 62))
        );

        jTabbedPane1.addTab("Job_Info", jPanel6);

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));

        jLabel41.setText("Job_ID");

        jLabel42.setText("Inmate_ID");

        jLabel43.setText("Shift");

        jLabel44.setText("Hours_Completed");

        jLabel45.setText("Feedback");

        Job_ID_Feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Job_ID_FeedbackActionPerformed(evt);
            }
        });

        Inmate_ID_Feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inmate_ID_FeedbackActionPerformed(evt);
            }
        });

        Shift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShiftActionPerformed(evt);
            }
        });

        Hours_Completed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hours_CompletedActionPerformed(evt);
            }
        });

        Submit_Job.setText("Insert");
        Submit_Job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_JobActionPerformed(evt);
            }
        });

        Feedback.setColumns(20);
        Feedback.setRows(5);
        jScrollPane3.setViewportView(Feedback);

        Update_Job.setText("Update");
        Update_Job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_JobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(jLabel44)
                    .addComponent(jLabel43)
                    .addComponent(jLabel42)
                    .addComponent(jLabel41))
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Submit_Job)
                        .addGap(18, 18, 18)
                        .addComponent(Update_Job))
                    .addComponent(Hours_Completed, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(Shift)
                    .addComponent(Inmate_ID_Feedback)
                    .addComponent(Job_ID_Feedback)
                    .addComponent(jScrollPane3))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(Job_ID_Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(Inmate_ID_Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(Shift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(Hours_Completed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit_Job)
                    .addComponent(Update_Job))
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Job", jPanel8);

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));

        jLabel35.setText("Name");

        jLabel36.setText("Contact_Number");

        jLabel37.setText("Inmate_ID");

        jLabel38.setText("Relationship");

        jLabel39.setText("Purpose");

        jLabel40.setText("Entry_time");

        Visitor_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Visitor_NameActionPerformed(evt);
            }
        });

        Contact_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contact_NumberActionPerformed(evt);
            }
        });

        Inmate_ID_Visitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inmate_ID_VisitorActionPerformed(evt);
            }
        });

        Relationship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelationshipActionPerformed(evt);
            }
        });

        Purpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurposeActionPerformed(evt);
            }
        });

        Entry_Time.setToolTipText("YYYY-MM-DD HH:MM:SS");
        Entry_Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entry_TimeActionPerformed(evt);
            }
        });

        Submit_Visitor.setText("Insert");
        Submit_Visitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_VisitorActionPerformed(evt);
            }
        });

        jLabel46.setText("Exit_time");

        Exit_Time.setToolTipText("YYYY-MM-DD HH:MM:SS");
        Exit_Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_TimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel39)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36)
                    .addComponent(jLabel35)
                    .addComponent(jLabel46))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Exit_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Submit_Visitor)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Entry_Time, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(Purpose, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Relationship, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Inmate_ID_Visitor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Contact_Number, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Visitor_Name, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(Visitor_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(Contact_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(Inmate_ID_Visitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(Relationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(Purpose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(Entry_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(Exit_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Submit_Visitor)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Visitor", jPanel7);

        jPanel10.setBackground(new java.awt.Color(51, 51, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(370, 236));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Insert Details");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prison_Management_System/Images/logout.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prison_Management_System/Images/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jLabel26)
                    .addComponent(jButton1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 51, 51));
        jPanel11.setPreferredSize(new java.awt.Dimension(370, 236));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("© Copyright 2017");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel47)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel47)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Case_ID_InmateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_ID_InmateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_ID_InmateActionPerformed

    private void JurisdictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JurisdictionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JurisdictionActionPerformed

    private void Staff_SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_SalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Staff_SalaryActionPerformed

    private void Staff_DesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_DesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Staff_DesignationActionPerformed

    private void Staff_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Staff_AddressActionPerformed

    private void Staff_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Staff_IDActionPerformed

    private void Staff_DoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_DoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Staff_DoBActionPerformed

    private void Job_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Job_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Job_IDActionPerformed

    private void Visitor_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Visitor_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Visitor_NameActionPerformed

    private void Contact_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contact_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Contact_NumberActionPerformed

    private void Inmate_ID_VisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inmate_ID_VisitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inmate_ID_VisitorActionPerformed

    private void RelationshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelationshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelationshipActionPerformed

    private void PurposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurposeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PurposeActionPerformed

    private void Entry_TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entry_TimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entry_TimeActionPerformed

    private void Job_ID_FeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Job_ID_FeedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Job_ID_FeedbackActionPerformed

    private void Inmate_ID_FeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inmate_ID_FeedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inmate_ID_FeedbackActionPerformed

    private void ShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShiftActionPerformed

    private void Hours_CompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hours_CompletedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hours_CompletedActionPerformed

    private void Submit_CaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_CaseActionPerformed
        int CaseID = Integer.parseInt(Case_ID.getText());
        String CaseType = Type.getText();
        //Check Type = civil or criminal
        String CaseVerdict = Verdict.getText();
        String VerdictDate = Verdict_Date.getText();
        int CourtID = Integer.parseInt(Court_ID_Case.getText());
        String CaseCharges = Charges.getText();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "INSERT INTO CASES VALUES('"+CaseID+"','"+CaseType+"','"+CaseVerdict+"','"+VerdictDate+"','"+CourtID+"');";
            stmt.executeUpdate(query);
            String line1 = "Inserted to Case & Charges" + CaseID + ", " + CaseType + ", " + CaseVerdict + ", " + VerdictDate + ", " + CourtID + ", " + CaseCharges; 
            String logger = "INSERT INTO LOG(User, Operation) VALUES('"+Login.username+"','"+line1+"');";
            stmt.executeUpdate(logger);
            String ChargeArr[] = CaseCharges.split(",");
            for(String temp: ChargeArr){
                query = "INSERT INTO CASE_CHARGES VALUES('"+CaseID+"','"+temp.trim()+"');";
                stmt.executeUpdate(query);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }   
    // TODO add your handling code here:
    }//GEN-LAST:event_Submit_CaseActionPerformed

    private void Submit_CourtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_CourtActionPerformed
        int CourtID = Integer.parseInt(Court_ID.getText());
        String CourtAddress = Address.getText();
        String ChiefJustice = Chief_Justice.getText();
        String CourtLevel = Level.getText();
        //Check level constraint here
        String JuryMembers = Jury.getText();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "INSERT INTO COURT VALUES('"+CourtID+"','"+CourtAddress+"','"+ChiefJustice+"','"+CourtLevel+"');";
            stmt.executeUpdate(query);
            String line1 = "Inserted to Court & Jury" + CourtID + ", " + CourtAddress + ", " + ChiefJustice + ", " + CourtLevel + ", " + JuryMembers; 
            String logger = "INSERT INTO LOG(User, Operation) VALUES('"+Login.username+"','"+line1+"');";
            stmt.executeUpdate(logger);
            String JuryArr[] = JuryMembers.split(",");
            for(String temp: JuryArr){
                query = "INSERT INTO COURT_JURY VALUES('"+CourtID+"','"+temp.trim()+"');";
                stmt.executeUpdate(query);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }         
    // TODO add your handling code here:
    }//GEN-LAST:event_Submit_CourtActionPerformed

    private void Submit_VisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_VisitorActionPerformed
        String VisitorName = Visitor_Name.getText();
        String Contact = Contact_Number.getText();
        int InmateID = Integer.parseInt(Inmate_ID_Visitor.getText());
        String VisitorRelationship = Relationship.getText();
        String VisitorPurpose = Purpose.getText();
        String EntryTime = Entry_Time.getText();
        String ExitTime = Exit_Time.getText();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "INSERT INTO VISITOR VALUES('"+VisitorName+"','"+Contact+"','"+InmateID+"','"+VisitorRelationship+"','"+VisitorPurpose+"','"+EntryTime+"','"+ExitTime+"');";
            stmt.executeUpdate(query);
            String line1 = "Inserted to Visitors" + VisitorName + ", " + Contact + ", " + InmateID + ", " + VisitorRelationship + ", " + VisitorPurpose + ", " + EntryTime + ", " + ExitTime; 
            String logger = "INSERT INTO LOG(User, Operation) VALUES('"+Login.username+"','"+line1+"');";
            stmt.executeUpdate(logger);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Submit_VisitorActionPerformed

    private void Start_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Start_DateActionPerformed

    private void Staff_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Staff_NameActionPerformed

    private void Exit_TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_TimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Exit_TimeActionPerformed

    private void Submit_Job_DescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_Job_DescActionPerformed
        String JobDesc = Job_Description.getText();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "INSERT INTO JOB_DESC (Description) VALUES('"+JobDesc+"');";
            stmt.executeUpdate(query);
            String line1 = "Inserted to Job Description" + JobDesc; 
            String logger = "INSERT INTO LOG(User, Operation) VALUES('"+Login.username+"','"+line1+"');";
            stmt.executeUpdate(logger);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_Submit_Job_DescActionPerformed

    private void Verdict_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Verdict_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Verdict_DateActionPerformed

    private void Submit_JobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_JobActionPerformed
        int JobID = Integer.parseInt(Job_ID_Feedback.getText());
        int InmateID = Integer.parseInt(Inmate_ID_Feedback.getText());
        String WorkShift = Shift.getText();
        //CHECK(Shift = 'morning' OR Shift = 'afternoon' OR Shift = 'evening' OR Shift = 'night')
        int HoursCompleted = Integer.parseInt(Hours_Completed.getText());
        String InmateFeedback = Feedback.getText();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "INSERT INTO JOB VALUES('"+JobID+"','"+InmateID+"','"+WorkShift+"','"+HoursCompleted+"','"+InmateFeedback+"');";
            stmt.executeUpdate(query);
            String line1 = "Inserted to Job" + JobID + ", " + InmateID + ", " + WorkShift + ", " + HoursCompleted + ", " + InmateFeedback; 
            String logger = "INSERT INTO LOG(User, Operation) VALUES('"+Login.username+"','"+line1+"');";
            stmt.executeUpdate(logger);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Submit_JobActionPerformed

    private void Case_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_IDActionPerformed

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeActionPerformed

    private void ChargesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChargesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChargesActionPerformed

    private void Submit_PrisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_PrisonActionPerformed
        String Location = Prison_Location.getText();
        String PrisonJurisdiction = Jurisdiction.getText();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "INSERT INTO PRISON (Location, Jurisdiction) VALUES('"+Location+"','"+PrisonJurisdiction+"');";
            stmt.executeUpdate(query);
            String line1 = "Inserted to Prison" + Location + ", " + PrisonJurisdiction;
            String logger = "INSERT INTO LOG(User, Operation) VALUES('"+Login.username+"','"+line1+"');";
            stmt.executeUpdate(logger);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Submit_PrisonActionPerformed

    private void Submit_StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_StaffActionPerformed
        String StaffName = Staff_Name.getText();
        String StaffDateOfBirth = Staff_DoB.getText();
        String StaffAddress = Staff_Address.getText();
        String StaffDesignation = Staff_Designation.getText();
        int StaffSalary = Integer.parseInt(Staff_Salary.getText());
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "INSERT INTO STAFF (Name, Date_Of_Birth, Address, Designation, Salary) VALUES('"+StaffName+"','"+StaffDateOfBirth+"','"+StaffAddress+"','"+StaffDesignation+"','"+StaffSalary+"');";
            stmt.executeUpdate(query);
            String line1 = "Inserted to Staff" + StaffName + ", " + StaffDateOfBirth + ", " + StaffAddress + ", " + StaffDesignation + ", " + StaffSalary;
            String logger = "INSERT INTO LOG(User, Operation) VALUES('"+Login.username+"','"+line1+"');";
            stmt.executeUpdate(logger);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Submit_StaffActionPerformed

    private void Submit_InmateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_InmateActionPerformed
        int InmateID = Integer.parseInt(Inmate_ID.getText());
        String InmateName = Inmate_Name.getText();
        String InmateAlias = Alias.getText();
        String InmateDateOfBirth = Inmate_DoB.getText();
        String StartDate = Start_Date.getText();
        String ReleaseDate = Release_Date.getText();
        int InmateCaseID = Integer.parseInt(Case_ID_Inmate.getText());
        int InmatePrisonID = Integer.parseInt(Prison_ID_Inmate.getText());
        int InmateSupervisorID = Integer.parseInt(Supervisor_Staff_ID.getText());
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "INSERT INTO INMATE VALUES('"+InmateID+"','"+InmateName+"','"+InmateDateOfBirth+"','"+StartDate+"','"+ReleaseDate+"','"+InmateCaseID+"','"+InmatePrisonID+"','"+InmateSupervisorID+"');";
            stmt.executeUpdate(query);
            String line1 = "Inserted to Inmate" + InmateID + ", " + InmateName + ", " + InmateAlias + ", " + InmateDateOfBirth + ", " + StartDate + ", " + ReleaseDate + ", " + InmateCaseID + ", " + InmatePrisonID + ", " + InmateSupervisorID;
            String logger = "INSERT INTO LOG(User, Operation) VALUES('"+Login.username+"','"+line1+"');";
            stmt.executeUpdate(logger);
            String Aliases[] = InmateAlias.split(",");
            for(String temp: Aliases){
                query = "INSERT INTO INMATE_ALIAS VALUES('"+InmateID+"','"+temp.trim()+"');";
                stmt.executeUpdate(query);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }    // TODO add your handling code here:
    }//GEN-LAST:event_Submit_InmateActionPerformed

    private void Update_CourtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_CourtActionPerformed
        int CourtID = Integer.parseInt(Court_ID.getText());
        String CourtAddress = Address.getText();
        String ChiefJustice = Chief_Justice.getText();
        String CourtLevel = Level.getText();
        String JuryMembers = Jury.getText();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "UPDATE COURT SET Address = '"+CourtAddress+"',Chief_Justice = '"+ChiefJustice+"',Level = '"+CourtLevel+"' WHERE Court_ID = '"+CourtID+"';";
            stmt.executeUpdate(query);
            query = "DELETE FROM COURT_JURY WHERE Court_ID = '"+CourtID+"';";
            stmt.executeUpdate(query);
            String JuryArr[] = JuryMembers.split(",");
            for(String temp: JuryArr){
                query = "INSERT INTO COURT_JURY VALUES('"+CourtID+"','"+temp.trim()+"');";
                stmt.executeUpdate(query);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }            // TODO add your handling code here:
    }//GEN-LAST:event_Update_CourtActionPerformed

    private void Update_CaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_CaseActionPerformed
        int CaseID = Integer.parseInt(Case_ID.getText());
        String CaseType = Type.getText();
        String CaseVerdict = Verdict.getText();
        String VerdictDate = Verdict_Date.getText();
        int CourtID = Integer.parseInt(Court_ID_Case.getText());
        String CaseCharges = Charges.getText();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "UPDATE CASES SET Type = '"+CaseType+"', Verdict = '"+CaseVerdict+"', Verdict_Date = '"+VerdictDate+"', Court_ID = '"+CourtID+"' WHERE Case_ID = '"+CaseID+"';";
            stmt.executeUpdate(query);
            query = "DELETE FROM CASE_CHARGES WHERE CASE_ID = '"+CaseID+"';";
            stmt.executeUpdate(query);
            String ChargeArr[] = CaseCharges.split(",");
            for(String temp: ChargeArr){
                query = "INSERT INTO CASE_CHARGES VALUES('"+CaseID+"','"+temp.trim()+"');";
                stmt.executeUpdate(query);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }    // TODO add your handling code here:
    }//GEN-LAST:event_Update_CaseActionPerformed

    private void Update_PrisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_PrisonActionPerformed
        int PrisonID = Integer.parseInt(Prison_ID.getText());
        String Location = Prison_Location.getText();
        String PrisonJurisdiction = Jurisdiction.getText();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "UPDATE PRISON SET Location = '"+Location+"', Jurisdiction = '"+PrisonJurisdiction+"' WHERE Prison_ID = '"+PrisonID+"';";
            stmt.executeUpdate(query);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Update_PrisonActionPerformed

    private void Update_StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_StaffActionPerformed
        int StaffID = Integer.parseInt(Staff_ID.getText());
        String StaffName = Staff_Name.getText();
        String StaffDateOfBirth = Staff_DoB.getText();
        String StaffAddress = Staff_Address.getText();
        String StaffDesignation = Staff_Designation.getText();
        int StaffSalary = Integer.parseInt(Staff_Salary.getText());
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "UPDATE STAFF SET Name = '"+StaffName+"', Date_Of_Birth = '"+StaffDateOfBirth+"', Address = '"+StaffAddress+"', Designation = '"+StaffDesignation+"', Salary = '"+StaffSalary+"' WHERE Staff_ID = '"+StaffID+"';";
            stmt.executeUpdate(query);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Update_StaffActionPerformed

    private void Update_InmateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_InmateActionPerformed
        int InmateID = Integer.parseInt(Inmate_ID.getText());
        String InmateName = Inmate_Name.getText();
        String InmateAlias = Alias.getText();
        String InmateDateOfBirth = Inmate_DoB.getText();
        String StartDate = Start_Date.getText();
        String ReleaseDate = Release_Date.getText();
        int InmateCaseID = Integer.parseInt(Case_ID_Inmate.getText());
        int InmatePrisonID = Integer.parseInt(Prison_ID_Inmate.getText());
        int InmateSupervisorID = Integer.parseInt(Supervisor_Staff_ID.getText());
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "UPDATE INMATE SET Name = '"+InmateName+"', Date_Of_Birth = '"+InmateDateOfBirth+"', Start_Date = '"+StartDate+"', Release_Date = '"+ReleaseDate+"', Case_ID = '"+InmateCaseID+"', Prison_ID = '"+InmatePrisonID+"', Supervisor_Staff_ID = '"+InmateSupervisorID+"' WHERE Inmate_ID = '"+InmateID+"';";
            stmt.executeUpdate(query);
            query = "DELETE FROM INMATE_ALIAS WHERE INMATE_ID = '"+InmateID+"';";
            stmt.executeUpdate(query);
            String Aliases[] = InmateAlias.split(",");
            for(String temp: Aliases){
                query = "INSERT INTO INMATE_ALIAS VALUES('"+InmateID+"','"+temp.trim()+"');";
                stmt.executeUpdate(query);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Update_InmateActionPerformed

    private void Update_Job_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_Job_InfoActionPerformed
        int JobID = Integer.parseInt(Job_ID.getText());
        String JobDesc = Job_Description.getText();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "UPDATE JOB_DESC SET Description = '"+JobDesc+"' WHERE Job_ID = '"+JobID+"';";
            stmt.executeUpdate(query);
            String line1 = "Updated Job Description" + JobDesc + "where Job_ID " + JobID; 
            String logger = "INSERT INTO LOG(User, Operation) VALUES('"+Login.username+"','"+line1+"');";
            stmt.executeUpdate(logger);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Update_Job_InfoActionPerformed

    private void Update_JobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_JobActionPerformed
        int JobID = Integer.parseInt(Job_ID_Feedback.getText());
        int InmateID = Integer.parseInt(Inmate_ID_Feedback.getText());
        String WorkShift = Shift.getText();
        int HoursCompleted = Integer.parseInt(Hours_Completed.getText());
        String InmateFeedback = Feedback.getText();
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String query = "UPDATE JOB SET Shift = '"+WorkShift+"', Hours_Completed = '"+HoursCompleted+"', Feedback = '"+InmateFeedback+"' WHERE Job_ID = '"+JobID+"' AND Inmate_ID = '"+InmateID+"';";
            stmt.executeUpdate(query);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Update_JobActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
            Statement stmt = (Statement)con.createStatement();
            String logger = "INSERT INTO LOG (User, Operation) VALUES('"+username+"',' Logout');";
            stmt.executeUpdate(logger);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        new Login().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(Login.access == 1)
            new AdministratorHome().setVisible(true);
        else if(Login.access == 2)
            new PrisonManagerHome().setVisible(true);
        else{
            JOptionPane.showMessageDialog(null, "Unstable State. Logging out");
            new Login().setVisible(true);
        }
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertOrUpdate_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertOrUpdate_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertOrUpdate_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertOrUpdate_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertOrUpdate_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Alias;
    private javax.swing.JTextField Case_ID;
    private javax.swing.JTextField Case_ID_Inmate;
    private javax.swing.JTextField Charges;
    private javax.swing.JTextField Chief_Justice;
    private javax.swing.JTextField Contact_Number;
    private javax.swing.JTextField Court_ID;
    private javax.swing.JTextField Court_ID_Case;
    private javax.swing.JTextField Entry_Time;
    private javax.swing.JTextField Exit_Time;
    private javax.swing.JTextArea Feedback;
    private javax.swing.JTextField Hours_Completed;
    private javax.swing.JTextField Inmate_DoB;
    private javax.swing.JTextField Inmate_ID;
    private javax.swing.JTextField Inmate_ID_Feedback;
    private javax.swing.JTextField Inmate_ID_Visitor;
    private javax.swing.JTextField Inmate_Name;
    private javax.swing.JTextArea Job_Description;
    private javax.swing.JTextField Job_ID;
    private javax.swing.JTextField Job_ID_Feedback;
    private javax.swing.JTextField Jurisdiction;
    private javax.swing.JTextField Jury;
    private javax.swing.JTextField Level;
    private javax.swing.JTextField Prison_ID;
    private javax.swing.JTextField Prison_ID_Inmate;
    private javax.swing.JTextField Prison_Location;
    private javax.swing.JTextField Purpose;
    private javax.swing.JTextField Relationship;
    private javax.swing.JTextField Release_Date;
    private javax.swing.JTextField Shift;
    private javax.swing.JTextField Staff_Address;
    private javax.swing.JTextField Staff_Designation;
    private javax.swing.JTextField Staff_DoB;
    private javax.swing.JTextField Staff_ID;
    private javax.swing.JTextField Staff_Name;
    private javax.swing.JTextField Staff_Salary;
    private javax.swing.JTextField Start_Date;
    private javax.swing.JButton Submit_Case;
    private javax.swing.JButton Submit_Court;
    private javax.swing.JButton Submit_Inmate;
    private javax.swing.JButton Submit_Job;
    private javax.swing.JButton Submit_Job_Desc;
    private javax.swing.JButton Submit_Prison;
    private javax.swing.JButton Submit_Staff;
    private javax.swing.JButton Submit_Visitor;
    private javax.swing.JTextField Supervisor_Staff_ID;
    private javax.swing.JTextField Type;
    private javax.swing.JButton Update_Case;
    private javax.swing.JButton Update_Court;
    private javax.swing.JButton Update_Inmate;
    private javax.swing.JButton Update_Job;
    private javax.swing.JButton Update_Job_Info;
    private javax.swing.JButton Update_Prison;
    private javax.swing.JButton Update_Staff;
    private javax.swing.JTextField Verdict;
    private javax.swing.JTextField Verdict_Date;
    private javax.swing.JTextField Visitor_Name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
