/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prison_Management_System;
import java.sql.*;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author amits
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Example1
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        usr_name = new javax.swing.JTextField();
        pass_field = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prison_Management_System/Images/send-secure.png"))); // NOI18N
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prison_Management_System/Images/lock-reset.png"))); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prison_Management_System/Images/cancel.png"))); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prison_Management_System/Images/account-location.png"))); // NOI18N
        Username.setText("Username");

        Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prison_Management_System/Images/textbox-password.png"))); // NOI18N
        Password.setText("Password");

        usr_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usr_nameFocusGained(evt);
            }
        });

        pass_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_fieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Login)
                        .addGap(10, 10, 10)
                        .addComponent(Reset)
                        .addGap(6, 6, 6)
                        .addComponent(Exit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(Password)
                        .addGap(63, 63, 63)
                        .addComponent(pass_field, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(Username)
                        .addGap(61, 61, 61)
                        .addComponent(usr_name, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(usr_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Password)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pass_field)
                        .addGap(2, 2, 2)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Login)
                    .addComponent(Reset)
                    .addComponent(Exit))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String username = usr_name.getText();
        String password = String.valueOf(pass_field.getPassword());
        String dbusername;
        String dbpassword;
        int access = 0, flag = 0;
        if(username.equals("") || password.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter username or password");
        }
        else{
            try{
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pms", "root", "26111996");
                PreparedStatement stmt = con.prepareStatement("SELECT * FROM USERS");
                ResultSet rs = stmt.executeQuery();
                while(rs.next()){
                    dbusername = rs.getString("username");
                    dbpassword = rs.getString("password");
                    access = Integer.parseInt(rs.getString("access"));
                    if(dbusername.equals(username)){
                        flag = 1;
                        if(dbpassword.equals(password)){
                            flag = 2;
                        }
                        else
                            JOptionPane.showMessageDialog(null, "Wrong Email or Password");
                        break;
                    }

                }
                if(flag == 0)
                    JOptionPane.showMessageDialog(null, "Not existing");
                else if(flag == 2){
                    if(access == 1)
                        new AdministratorHome().setVisible(true);
                    else if(access == 2)
                        new PrisonManagerHome().setVisible(true);
                    else
                        new Search().setVisible(true);
                    this.dispose();
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
          
// TODO add your handling code here:
    }//GEN-LAST:event_LoginActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        usr_name.setText("");
        pass_field.setText("");
    // TODO add your handling code here:
    }//GEN-LAST:event_ResetActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void usr_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usr_nameFocusGained
              // TODO add your handling code here:
    }//GEN-LAST:event_usr_nameFocusGained

    private void pass_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_fieldFocusGained
             // TODO add your handling code here:
    }//GEN-LAST:event_pass_fieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Password;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel Username;
    private javax.swing.JPasswordField pass_field;
    private javax.swing.JTextField usr_name;
    // End of variables declaration//GEN-END:variables
}
